### ISSUE TITLE
Can't use sourcery because the binary is not found

### ISSUE THREAD

**Issue by rhytnen** [sourcery-ai/public#21]
### Issue description or question
Can't use sourcery because it fails to find the binary during configuration
![image](https://user-images.githubusercontent.com/632888/73975116-86365700-48da-11ea-90bc-de7cfefe00c3.png)

This may well be an issue with my work network though my other plugins do not have this issue.  Is it possible to download the plugin and install it manually?

### Sourcery Version
All versions

### Code editor or IDE name and version

Pycharm v?
2019.3

### OS name and version
Windows 10

**Comment by rhytnen** [comment]
After reading the plugin XML and finding the exe is in fact installed, the issue is that by policy i can't execute binaries in roaming.  Is there a way to configure the installation location to a place i can use?

**Comment by Hellebore** [comment]
Oh interesting. I'll look into making that more configurable. It's stored in sourceryExecutable in a sourcery.xml file in PyCharm but I'm not sure where this lives on Windows.

Did you also have an issue with Sourcery taking up lots of disk space? Would also be great to solve that one if you have more details.

**Comment by rhytnen** [comment]
On windows, the xml file lives here: C:\Users\rossh\.PyCharm2019.3\config\options

I went so far as to edit the path listed there but when restarting the IDE, it seems like it redownloads the plugin and rewrites the xml.  Then I tried write protecting the xml, but it errors because it can't write it's settings.  

Re: the large disk space usage, that is on my home pc.  I was shocked to see it taking 10s of gigs.  When I get home I'll see what kind of information I can dig up.

**Comment by Hellebore** [comment]
We've decided to switch to bundling the binary with the plugin. This will mean that it runs from within wherever Pycharm is installed, which should fix the AppData/Roaming problem.

It's submitted to IntelliJ - will let you know when it's approved and you can test the new version.

**Comment by Hellebore** [comment]
OK the new version of the plugin (0.3.0) is now available. It would be great if you could try it out to see if it resolves your issue.

To install it go to File > Settings > Plugins and update Sourcery via the Update tab.

**Comment by rhytnen** [comment]
Wow!  Thanks so much - that works perfectly.  I'm happy to donate my time to an issue or two to any open parts of your project as a thank you.

I'll monitor my disk usage and let you know about the space issue.  If I see it again I'll open an issue.

**Comment by Hellebore** [comment]
No problem!  What we need most of all right now is feedback so please do keep opening issues with problems/improvements we could make.
